In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [2]:
data = pd.read_csv(r"C:\Users\sindhuja\Downloads\archive\Housing.csv")
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
data.shape

(545, 13)

In [4]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [6]:
data.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [7]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [8]:
data_encoded = pd.get_dummies(data, drop_first=True)

In [9]:
X = data_encoded.drop("price", axis=1)
y = data_encoded["price"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [11]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = model.predict(X_test)

In [13]:
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("R² Score:", r2)
print("Mean Squared Error:", mse)

R² Score: 0.6529242642153184
Mean Squared Error: 1754318687330.6643

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [16]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [17]:
y_pred_rf = rf_model.predict(X_test)

In [18]:
rf_r2 = r2_score(y_test, y_pred_rf)
rf_mse = mean_squared_error(y_test, y_pred_rf)

print("Random Forest R² Score:", rf_r2)
print("Random Forest Mean Squared Error:", rf_mse)

Random Forest R² Score: 0.611918531405699
Random Forest Mean Squared Error: 1961585044320.3433

In [19]:
comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "R2 Score": [r2, rf_r2],
    "Mean Squared Error": [mse, rf_mse]
})

comparison

               Model  R2 Score  Mean Squared Error
0  Linear Regression  0.652924        1.754319e+12
1      Random Forest  0.611919        1.961585e+12

In [21]:
sample_house = X_test.iloc[[0]]
sample_house

,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
316,5900,4,2,2,1,False,False,True,False,False,False,False,True

In [22]:
actual_price = y_test.iloc[0]
print("Actual House Price:", actual_price)

Actual House Price: 4060000

In [23]:
lr_pred_price = model.predict(sample_house)
print("Predicted Price (Linear Regression):", lr_pred_price[0])

Predicted Price (Linear Regression): 5164653.900339671

In [24]:
rf_pred_price = rf_model.predict(sample_house)
print("Predicted Price (Random Forest):", rf_pred_price[0])

Predicted Price (Random Forest): 5377680.0

In [25]:
prediction_comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "Predicted Price": [lr_pred_price[0], rf_pred_price[0]],
    "Actual Price": [actual_price, actual_price]
})

prediction_comparison

               Model  Predicted Price  Actual Price
0  Linear Regression     5.164654e+06       4060000
1      Random Forest     5.377680e+06       4060000